# Simple Linear Regression. Minimal example

### Import the relevant libraries

In [2]:
# We must always import the relevant libraries for our problem at hand. NumPy is a must for this example.
import numpy as np

# matplotlib and mpl_toolkits are not necessary. We employ them for the sole purpose of visualizing the results.  
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [3]:
obs = 1000

In [4]:
xs = np.random.uniform(low=-10,high=10,size = (obs,1))
zs = np.random.uniform(low=-10,high=10,size = (obs,1))

In [5]:
inputs = np.column_stack((xs,zs))

In [6]:
inputs.shape

(1000, 2)

In [7]:
noise = np.random.uniform(-1,1,(obs,1))

In [8]:
targets = 2*xs - 3*zs+5 +noise

In [9]:
targets.shape

(1000, 1)

In [10]:
init_range = 0.1
weights = np.random.uniform(-init_range,init_range,(2,1))
bias = np.random.uniform(-init_range,init_range,(1,1))

print(weights)
print(bias)

[[0.05669452]
 [0.05018133]]
[[-0.07015709]]


In [11]:
learning_rate = 0.02

In [12]:
for i in range(1,1000):
    outputs = np.dot(inputs,weights) + bias
    deltas = outputs - targets
    cost = np.sum(deltas**2)/2/obs
    print(cost)
    deltas_scaled = deltas / obs
    weights = weights - learning_rate * np.dot(inputs.T,deltas_scaled)
    bias = bias - learning_rate * np.sum(deltas_scaled)

225.86609937105266
38.8647211672459
15.235062082285978
11.894444738542376
11.089525220439773
10.615121672849654
10.196623065489927
9.799306161518558
9.41828985281203
9.052426101044192
8.701052593034936
8.363588003178588
8.039480830238809
7.72820225007951
7.429244475622866
7.142119831784141
6.866359947915371
6.6015149922801575
6.347152938081775
6.10285885869879
5.868234250835502
5.642896384465436
5.4264776785051385
5.218625101199688
5.018999594241692
4.827275519684388
4.643140128746658
4.46629305164337
4.296445807608939
4.133321334314749
3.9766535359128308
3.826186848968574
3.6816758255743514
3.5428847329640463
3.409587168975363
3.281565692732598
3.158611469947487
3.040523932259496
2.9271104500598244
2.818186018265506
2.7135729545309206
2.613100609404516
2.5166050879578767
2.4239289824330768
2.334921115472187
2.249436293510099
2.1673350699283587
2.088483517583681
2.012753010340079
1.9400200132482333
1.8701658810298123
1.803076664538064
1.7386429248789277
1.6767595548894731
1.61732560768

0.1751923404676636
0.17519234045834134
0.17519234044938808
0.17519234044078924
0.17519234043253068
0.17519234042459902
0.1751923404169813
0.17519234040966525
0.1751923404026386
0.17519234039589013
0.17519234038940884
0.175192340383184
0.1751923403772056
0.17519234037146375
0.17519234036594933
0.17519234036065295
0.17519234035556636
0.1751923403506811
0.17519234034598918
0.17519234034148295
0.17519234033715503
0.17519234033299855
0.17519234032900657
0.17519234032517256
0.17519234032149028
0.17519234031795383
0.17519234031455722
0.17519234031129513
0.1751923403081622
0.17519234030515324
0.17519234030226336
0.17519234029948785
0.17519234029682218
0.17519234029426206
0.1751923402918033
0.17519234028944186
0.17519234028717384
0.1751923402849956
0.17519234028290365
0.17519234028089448
0.17519234027896477
0.1751923402771115
0.17519234027533157
0.17519234027362204
0.1751923402719802
0.1751923402704034
0.1751923402688889
0.17519234026743455
0.17519234026603758
0.17519234026469596
0.175192340263

In [13]:
weights

array([[ 1.99708151],
       [-3.00552147]])

In [14]:
bias

array([[4.9890668]])