In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv('1.02.Multiple-linear-regression (1).csv')


In [4]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [5]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [6]:
x = data[['SAT','Rand 1,2,3']]

In [7]:
y=data['GPA']

In [8]:
reg = LinearRegression()

In [9]:
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [11]:
reg.intercept_

0.29603261264909486

In [12]:
R = reg.score(x,y)

### formula for adjused R^2
$R^2_(adj.) = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [13]:
x.shape

(84, 2)

In [14]:
n=x.shape[0]
n

84

In [15]:
p = x.shape[1]
p

2

In [16]:
R_adj= 1 - (1-R)*(n-1)/(n-p-1)

In [17]:
from sklearn.feature_selection import f_regression

In [18]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [19]:
p_value = f_regression(x,y)[1]
p_value

array([7.19951844e-11, 6.76291372e-01])

In [20]:
p_value.round(3)

array([0.   , 0.676])

In [21]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['featuers'])
reg_summary['coefficients'] = reg.coef_
reg_summary['p_value'] = p_value.round(3)

display(reg_summary)

featuers  coefficients  p_value
0         SAT      0.001654    0.000
1  Rand 1,2,3     -0.008270    0.676

# Standardization:


In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
scaler = StandardScaler()

In [24]:
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [25]:
x_scaled = scaler.transform(x)

In [26]:
scaled_reg = LinearRegression()

In [27]:
scaled_reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
scaled_reg.coef_

array([ 0.17181389, -0.00703007])

In [29]:
p_value = f_regression(x_scaled,y)[1]
p_value.round(3)

array([0.   , 0.676])

In [30]:
scaled_reg_summery = pd.DataFrame(['intercept' , 'SAT' , 'Rand 1, 2, 3'], columns = ['features'])
scaled_reg_summery['weights'] = scaled_reg.intercept_, scaled_reg.coef_[0], scaled_reg.coef_[1]
scaled_reg_summery

features   weights
0     intercept  3.330238
1           SAT  0.171814
2  Rand 1, 2, 3 -0.007030

# prediction

In [31]:
new_data = pd.DataFrame([[1700,2],[1800,1]], columns=['SAT','rand'])

In [32]:
new_data

SAT  rand
0  1700     2
1  1800     1

In [33]:
reg.predict(new_data)

array([3.09051403, 3.26413803])

In [34]:
scaled_reg.predict(new_data)

array([295.39979563, 312.58821497])

In [35]:
new_data_scaled = scaler.transform(new_data)

In [36]:
scaled_reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

# Train Test Split

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
a = np.arange(1,101)

In [39]:
b = np.arange(501,601)

In [40]:
a_train, a_text = train_test_split(a)

In [41]:
a_train.shape

(75,)

In [42]:
a_train, a_test, b_train, b_test = train_test_split(a,b, test_size=0.2, random_state=42)

In [43]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [44]:
b_train

array([556, 589, 527, 543, 570, 516, 541, 597, 510, 573, 512, 548, 586,
       529, 594, 506, 567, 566, 536, 517, 550, 535, 508, 596, 528, 520,
       582, 526, 563, 514, 525, 504, 518, 539, 509, 579, 507, 565, 537,
       590, 557, 600, 555, 544, 551, 568, 547, 569, 562, 598, 580, 542,
       559, 549, 599, 558, 576, 533, 595, 560, 564, 585, 538, 530, 502,
       553, 522, 503, 524, 588, 592, 575, 587, 583, 521, 561, 572, 515,
       593, 552])